services:
  - type: web
    name: madrin-md-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SESSION_ID
        sync: false # You will paste your long code in the dashboard
      - key: MODE
        value: public
      - key: OWNER_NUMBER
        value: "255780309253"
      - key: BOT_NAME
        value: "balckthrone"
      - key: PORT
        value: "3000"
      - key: NODE_VERSION
        value: "20.x"
